name: Go Lint

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.24.x

    - name: Check out code
      uses: actions/checkout@v2

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest